version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: rag_postgres
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_network

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.15
    container_name: rag_neo4j
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - rag_network

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rag_network

  # RAG Application
  rag_app:
    build: .
    container_name: rag_application
    ports:
      - "8005:8005"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - neo4j
      - qdrant
      - redis
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    networks:
      - rag_network

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  qdrant_data:
  redis_data:

networks:
  rag_network:
    driver: bridge
